language: Java
before_install:
 - chmod +x gradlew
jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: generatePomFile
      script: ./gradlew generatePomFileForBintrayPublicationPublication
    - stage: deploy
      script: ./gradlew -Pbintray-user=${bintrayUser} -Pbintray-key=${bintrayKey} bintrayUpload -x clean


